name: Run Tests and Publish Allure

on:
  schedule:
    - cron: '0 */12 * * *'    
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Node setup
      - uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Install dependencies for API tests
      - name: Install API dependencies
        working-directory: APITest.DummyJSON
        run: npm ci

      # Install dependencies for UI tests
      - name: Install UI dependencies
        working-directory: UITest.SauceDemo
        run: npm ci

       # Install Playwright browsers
      - name: Install Playwright Browsers
        working-directory: UITest.SauceDemo
        run: npx playwright install --with-deps

      # Setup Allure
      - name: Install Allure Commandline
        run: npm install -g allure-commandline@2.36.0

      # Run API tests
      - name: Run API tests
        working-directory: APITest.DummyJSON
        run: npx codeceptjs run --steps --plugins allure
        continue-on-error: true    

      # Run UI tests
      - name: Run UI tests
        working-directory: UITest.SauceDemo
        run: npx codeceptjs run --steps --plugins allure
      

      # Combine allure-results from API and UI
      - name: Combine Allure results
        run: |
          mkdir -p combined-allure-results
          cp -r APITest.DummyJSON/allure-results/* combined-allure-results/ || true
          cp -r UITest.SauceDemo/allure-results/* combined-allure-results/ || true

      # Generate HTML report
      - name: Generate Allure HTML
        run: npx allure generate combined-allure-results --clean -o allure-report

      # Upload result as artifact 
      - name: Upload Allure Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: allure-results
         path: combined-allure-results


      # Deploy to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./allure-report
          publish_branch: allure-report  
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish Allure Report from workflow'
