name: Run Tests and Publish Allure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Node setup
      - uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Install dependencies for API tests
      - name: Install API dependencies
        working-directory: APITest.DummyJSON
        run: npm ci

      # Install dependencies for UI tests
      - name: Install UI dependencies
        working-directory: UITest.SauceDemo
        run: npm ci

       # Install Playwright browsers
      - name: Install Playwright Browsers
        working-directory: UITest.SauceDemo
        run: npx playwright install --with-deps

      # Setup Allure
      - name: Install Allure Commandline
        run: npm install -g allure-commandline@2.36.0

      # Run API tests
      - name: Run API tests
        working-directory: APITest.DummyJSON
        run: npx codeceptjs run
        continue-on-error: true    

      # Run UI tests
      - name: Run UI tests
        working-directory: UITest.SauceDemo
        run: npx codeceptjs run
        continue-on-error: true
      

      # Combine allure-results from API and UI
     # - name: Combine Allure results
     #   run: |
      #    mkdir -p combined-allure-results
       #   cp -r APITest.DummyJSON/allure-results/* combined-allure-results/ || true
        #  cp -r UITest.SauceDemo/allure-results/* combined-allure-results/ || true

      # Generate HTML report
      #- name: Generate Allure HTML
       # run: npx allure generate combined-allure-results --clean -o allure-report

      # Deploy to GitHub Pages
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
         gh_pages: gh-pages
         allure_history: allure-history
         allure_results: build/allure-results
         
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
         
       
        
